name: Deploy to WordPress

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Deploy to server
      uses: appleboy/ssh-action@v0.1.5
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /tmp
          wget https://github.com/Ahmadh24/You-Know-it-Cards/archive/main.zip
          unzip -o main.zip
          sudo cp -r You-Know-it-Cards-main/* /var/www/html/wp-content/themes/blocksy-child/
          sudo chown -R www-data:www-data /var/www/html/wp-content/themes/blocksy-child/
          rm -rf You-Know-it-Cards-main main.zip
